# Model Configuration
model:
  name: "DCFF"
  backbone: "resnet18"
  attention_dims: [128, 256, 512]
  classifier_dims: 128

# Training Parameters
training:
  epochs: 100
  batch_size: 32
  learning_rate: 0.001
  optimizer: "adam"
  loss: "focal"
  gamma: 2.0

# Data Configuration
data:
  input_size: [256, 256]
  dataset_path: "./data/giad"
  train_split: 0.8
  augmentations:
    noise_sigma: 0.1
    overlay_prob: 0.3
    affine: True

# Hardware Settings
hardware:
  device: "cuda"
  precision: "fp16"
  workers: 4